import { useRouter } from 'next/router';
import Header from './header';
import Footer from './footer';
import Head from 'next/head';
import React from 'react';

// 

export default function Layout({ children }){

    return (
       <>
        <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>   
        <title>Animal</title>
        </Head> 
        <Header/>
        <main className='container-fluid'>{children}</main>
        <Footer />
       </>
    )
}